_security_logout:
    resource: security.route_loader.logout
    type: service

security:
    providers:
        users:
            entity:

                class: 'App\Entity\User'

                property: 'email'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            logout:
            role_hierarchy:
                ROLE_USER: ['ROLE_USER']
                ROLE_ADMIN: ['ROLE_ADMIN']
                ROLE_BANNED: ['ROLE_BANNED']

    password_hashers:

        App\Entity\User: 'auto'

        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: 'auto'
            cost: 15
